name: flutter_draftea_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  path_provider: ^2.1.1
  go_router: ^17.0.1
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.1
  build_runner: ^2.10.5


flutter:
  uses-material-design: true
